service: playlist-service

provider:
  name: aws
  runtime: nodejs4.3
  profile: personal-admin
  region: eu-west-1
functions:
  playlist:
    handler: handler.Playlist
    events:
      - http:
          path: playlist 
          method: get
  authorizerFunc:
    handler: handler.Authorise
